### ISSUE TITLE
libcurl error

### ISSUE THREAD

**Issue by jeffreypullin** [lionel-/contributing#1]
Hi Lionel, 

I realise it's a little early for you to be accepting contributions just yet but I've been playing along at home and ran into the error:

```
error: libcurl >= 7.28.0 library and headers are required with support for https
```

I was able to fix it with by taking anaconda3 off the path following this [answer](https://stackoverflow.com/questions/38690232/installing-r-on-linux-configure-error-libcurl-7-28-0-library-and-headers-a).

Would you consider adding this to Compilation troubleshooting section? I'd be happy to make a PR if so.

All the best!

**Comment by lionel-** [comment]
yes please!
